### PR TITLE
Add automatic version detection to Javadoc badge

### PR DESCRIPTION
**Pull request by valery1707**

### CODE REVIEW

**Comment by dmarkov** [comment]
@valery1707 Thanks for the pull request, let me find a reviewer..

**Comment by dmarkov** [comment]
@yegor256 the PR is rather short, please review it

**Comment by yegor256** [comment]
@valery1707 thanks!

**Comment by dmarkov** [comment]
@yegor256 Much obliged! I have added **16 mins** to your account in payment "000-b02fb3e9", 7292 hours and 2 mins spent; you're getting extra minutes here (c=1); added +16 to your rating, now it is equal to [+49](http://www.netbout.com/b/35008?open=rating)

**Comment by dmarkov** [comment]
@rultor deploy now pls

**Pull request merged**
