### PR TITLE
update for @NotNull annotations are inconsistently used

### PR DESCRIPTION
**Pull request by simonjenga**
#56  update for @NotNull annotations are inconsistently used

### CODE REVIEW

**Comment by dmarkov** [comment]
@simonjenga Thanks, let me find someone who can review this pull request

**Comment by dmarkov** [comment]
@pinaf please review this one

**Comment by pinaf** [comment]
@simonjenga looks good to me.
@Suseika what do you think?

**Comment by Suseika** [comment]
@simonjenga Looks fine, but how come you haven't been assigned on this issue by a project manager?

**Comment by pinaf** [comment]
@rultor merge

**Comment by simonjenga** [comment]
@pinaf Good to hear from you!

@Suseika Ideally that is how it should be. Remember, these projects are ```Open source```. You can decide to wait for the PM to assign you the issue(s) or you can decide to take the initiative yourself.

As long as the contributions being made to a project do not violate the PM's quality standard's, i do not see why a PR should not be submitted by anyone at anytime.

**Comment by yegor256** [comment]
@rultor try to merge

**Comment by dmarkov** [comment]
@pinaf thank you, added **17 mins** to your acc, payment num is `AP-3R110299FV524131D`, 95 hours and 2 mins spent in total to complete; review comments (c=2) added as a bonus; added +17 to your rating, now it is equal to [+4251](http://www.netbout.com/b/35128?open=rating)

**Comment by dmarkov** [comment]
@rultor deploy pls

**Pull request merged**
