### PR TITLE
Update AwsIteratorITCase.java

### PR DESCRIPTION
**Pull request by jrdalpra**
Just removing the TODO from source code.

### CODE REVIEW

**Comment by dmarkov** [comment]
@jrdalpra Many thanks, I will find someone to review it before we merge

**Comment by dmarkov** [comment]
@yegor256 review it please, it is a rather short pull request, no need to do a full code review

**Comment by yegor256** [comment]
@jrdalpra why are you removing it? I don't understand the context of this change...

**Comment by jrdalpra** [comment]
@yegor256 @dmarkov asked if I removed the puzzle. The puzzle was solved (see https://github.com/jcabi/jcabi-dynamo/pull/68), but I forgot to remove the "TODO" that refers to the puzzle. This PR simply removes the TODO at javadoc. Simple.

**Comment by yegor256** [comment]
@rultor merge

**Comment by dmarkov** [comment]
@yegor256 Thank you, I have added **17 mins** to your account in payment/transaction "`000-aa38322f`", time consumed: 20 hours and 9 mins; you're getting extra minutes here (c=2); +17 added to your rating, at the moment it is: [+7421](http://www.netbout.com/b/35008?open=rating)

**Comment by dmarkov** [comment]
@rultor deploy

**Pull request merged**
