### PR TITLE
bugfix: Remove instance of operators

### PR DESCRIPTION
**Pull request by sandordargo**

### CODE REVIEW

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this pull request

**Comment by 0crat** [comment]
Job `gh:jcabi/jcabi-dynamo#91` is in scope.

**Comment by sandordargo** [comment]
@yegor256 seems that there are some environmental issues with the builds. Given the nature of my changes, most probably they have been already around. Do you have any clue?

**Comment by yegor256** [comment]
@rultor merge

**Comment by yegor256** [comment]
@sandordargo thanks!

**Pull request merged**
