### PR TITLE
#49 Refactoring MkData to eliminate table name.

### PR DESCRIPTION
**Pull request by super132**
For task #49 

- Refactor `MkData` to eliminate table name in all methods.
- Modified `H2Data` implementation for the interface changes
- Modified unit tests.

### CODE REVIEW

**Comment by super132** [comment]
@dmarkov Please review this PR. Thanks.

**Comment by dmarkov** [comment]
@super132 Thanks, someone will review your pull request soon

**Comment by dmarkov** [comment]
@ggajos please review, thanks

**Comment by dmarkov** [comment]
> @dmarkov Please review this PR. Thanks.

@super132 thanks, I'll take a look

**Comment by ggajos** [comment]
@super132 some checks failed

**Comment by super132** [comment]
@ggajos The travis fail build was due to unable to download a artifact from Maven. I think it does not indicate there is any problem in the codes. Thanks.

**Comment by ggajos** [comment]
@super132 for me this is looking good

**Comment by ggajos** [comment]
@rultor merge please

**Comment by yegor256** [comment]
@super132 I posted a comment here: https://github.com/jcabi/jcabi-dynamo/issues/49#issuecomment-123961177 Let's resolve it there and then will decided what to do here, thanks!

**Comment by super132** [comment]
@yegor256 should I close this PR ? Thanks.

**Comment by yegor256** [comment]
@super132 yes, please close it. we won't merge

**Comment by dmarkov** [comment]
@ggajos I just added **18 mins** to your account, many thanks for your contribution (AP-3KH16006M5453454W).. 148 hours and 53 mins spent here

review comments (c=3) added as a bonus

+18 added to your rating, at the moment it is: [+540](http://www.netbout.com/b/35094?open=rating)

**Pull request closed without merging**
