### PR TITLE
#22 - update copyright to 2015

### PR DESCRIPTION
**Pull request by nathansgreen**

### CODE REVIEW

**Comment by dmarkov** [comment]
Thanks for the pull request, let me find a reviewer..

**Comment by dmarkov** [comment]
@krzyk please review

**Comment by krzyk** [comment]
@rultor merge pls

**Comment by yegor256** [comment]
@rultor merge pls

**Comment by dmarkov** [comment]
@krzyk Thank you, I've added **16 mins** to your account in payment/transaction "`50518832`"... added +16 to your rating, now it is equal to [+2035](http://www.netbout.com/b/35035?open=rating)

**Comment by dmarkov** [comment]
@rultor deploy now pls

**Pull request merged**
