### PR TITLE
Build failed on windows with lots of EOL violations

### PR DESCRIPTION
**Pull request by simonjenga**
#42 Build failed on windows with lots of EOL violations

### CODE REVIEW

**Comment by dmarkov** [comment]
@simonjenga Thanks, someone will review your pull request soon

**Comment by dmarkov** [comment]
@yegor256 review this pls (it's a rather short pull request)

**Comment by yegor256** [comment]
@rultor merge it pls

**Comment by dmarkov** [comment]
@yegor256 **16 mins** sent to your balance (ID `000-67e8542c`), many thanks! It took 21 hours and 47 mins.... review comments (c=1) added as a bonus... +16 added to your rating, at the moment it is: [+6172](http://www.netbout.com/b/35008?open=rating)

**Comment by dmarkov** [comment]
@rultor deploy now pls

**Comment by yegor256** [comment]
@simonjenga build is passing now on appveyor

**Pull request merged**
