### PR TITLE
Removed puzzle and ignore

### PR DESCRIPTION
**Pull request by amihaiemil**
This PR is for issue #65 . I removed the puzzle and the ``Ignore`` annotation. After this puzzle was created, the validation api was removed (issue #69, commit 049577d89f405d4ee24ff01388bfb83c9e416b13) .

### CODE REVIEW

**Comment by dmarkov** [comment]
@amihaiemil Thanks, I will ask someone to do a code review here, thanks for your pull request

**Comment by dmarkov** [comment]
@yegor256 review this pls (it's a rather short pull request)

**Comment by amihaiemil** [comment]
@yegor256 Can you merge this pls? Thanks.

**Comment by yegor256** [comment]
@rultor try to merge

**Comment by dmarkov** [comment]
@yegor256 thanks, paid, **16 mins** to your account, payment ID is `000-7ff462e3`, task took 97 hours and 50 mins to complete. you're getting extra minutes here (c=1). added +16 to your rating, now it is equal to [+1695](http://www.netbout.com/b/35008?open=rating)

**Comment by dmarkov** [comment]
@rultor deploy

**Pull request merged**
